[package]
name = "rct_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rct_derive = {path = "../rct_derive"}
rct = {path = "../rct"}
